/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          blue:     '#004BD6',
          darkblue: '#062B8F',
          neon:     '#DFFF00',
          neonHover:'#C6E800',
          accent:   '#FFFF00',
          black:    '#101114',
        },
        outline: "#737686",
        "surface-container": "#ecedf8",
        background: "#f9f9ff",
        "surface-dim": "#d8d9e4",
        "primary-container": "#004bd6",
        "on-primary-fixed-variant": "#003cae",
        "surface-variant": "#e1e2ec",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#181e00",
        primary: "#0037a2",
        "surface-container-low": "#f2f3fe",
        "on-background": "#191b23",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b6d300",
        "inverse-on-surface": "#eff0fb",
        "tertiary-fixed": "#dde1ff",
        "surface-tint": "#1351dc",
        "on-surface-variant": "#434655",
        surface: "#f9f9ff",
        tertiary: "#233b8d",
        "primary-fixed": "#dce1ff",
        "surface-container-high": "#e6e7f2",
        "on-primary-fixed": "#00164e",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#c2ceff",
        secondary: "#566500",
        "on-secondary-fixed-variant": "#404c00",
        "tertiary-fixed-dim": "#b7c4ff",
        "on-tertiary-fixed": "#001453",
        "secondary-fixed": "#d0f100",
        "secondary-container": "#ceee00",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e2ec",
        "primary-fixed-dim": "#b5c4ff",
        error: "#ba1a1a",
        "outline-variant": "#c3c5d7",
        "inverse-surface": "#2d3038",
        "tertiary-container": "#3d53a6",
        "on-secondary-container": "#5a6900",
        "surface-bright": "#f9f9ff",
        "error-container": "#ffdad6",
        "inverse-primary": "#b5c4ff",
        "on-surface": "#191b23",
        "on-tertiary-fixed-variant": "#294092",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#c4ceff",
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        margin: "2rem",
        "gutter-mobile": "1rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        sans: ['"Space Grotesk"', 'sans-serif'],
        pixel: ['"Silkscreen"', 'monospace'],
        "headline-sm": ['"Space Grotesk"', 'sans-serif'],
        "title-md": ['"Outfit"', 'sans-serif'],
        "headline-md": ['"Space Grotesk"', 'sans-serif'],
        "body-lg": ['"Outfit"', 'sans-serif'],
        "headline-lg": ['"Space Grotesk"', 'sans-serif'],
        "label-md": ['"Space Mono"', 'monospace'],
        "label-sm": ['"Space Mono"', 'monospace'],
        "label-lg": ['"Space Mono"', 'monospace'],
        "headline-lg-mobile": ['"Space Grotesk"', 'sans-serif'],
        "body-md": ['"Outfit"', 'sans-serif'],
        "headline-xl": ['"Space Grotesk"', 'sans-serif'],
        "headline-xl-mobile": ['"Space Grotesk"', 'sans-serif'],
      },
      fontSize: {
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      boxShadow: {
        'brutal-sm':    '3px 3px 0px 0px #000',
        'brutal':       '5px 5px 0px 0px #000',
        'brutal-lg':    '8px 8px 0px 0px #000',
        'brutal-neon':  '6px 6px 0px 0px #DFFF00',
        'brutal-white': '6px 6px 0px 0px #ffffff',
      },
      borderWidth: {
        '3': '3px',
      },
    },
  },
  plugins: [],
}
